
print("INSERTING VALUES: ")
PyLL=LinkedList()
PyLL.insertInempty(100)
PyLL.insertBegin(30)
PyLL.insertEnd(40)
PyLL.insertBegin(30)
PyLL.insertEnd(100)
PyLL.insertAfterGivenNode(20,40)
PyLL.insertBeforeGivenNode(10,30)
PyLL.display()
print("*****************")
print("REVERSING VALUES: ")
PyLL.reverseLinkedList()
PyLL.display()
print("*****************")
print("SORTING: ")
PyLL.sortingList()
PyLL.display()
print("*****************")
print("OTHERS: ")
index=PyLL.findIndex(30)
print(index)
print(len(PyLL))
maxnum=PyLL.maximumInLL()
print(maxnum)
minnum=PyLL.minimumInLL()
print(minnum)
print("*****************")
print("Remove Duplicates: ")
PyLL.removeDuplicates()
PyLL.display()
print("*****************")
print("DELETING VALUES: ")
PyLL.deleteBegin()
PyLL.deleteEnd()
PyLL.deleteByValue(30)
PyLL.display()
